// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWmxw_ZP1VwVFNFwgyXL8kGC8ofug_JY',
    appId: '1:140433520926:web:8b12a7f894345fcaa9b10f',
    messagingSenderId: '140433520926',
    projectId: 'app-lista-tarefas-fatec-noite',
    authDomain: 'app-lista-tarefas-fatec-noite.firebaseapp.com',
    storageBucket: 'app-lista-tarefas-fatec-noite.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_4C0bHxCgh4aUNxuXoxu0SHmp9obJRY',
    appId: '1:140433520926:android:2744b6913a9d4ac0a9b10f',
    messagingSenderId: '140433520926',
    projectId: 'app-lista-tarefas-fatec-noite',
    storageBucket: 'app-lista-tarefas-fatec-noite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYMIfI9tBA3dvqX0Bc-qVGUh-R4lJslI',
    appId: '1:140433520926:ios:34bebb2e417d8782a9b10f',
    messagingSenderId: '140433520926',
    projectId: 'app-lista-tarefas-fatec-noite',
    storageBucket: 'app-lista-tarefas-fatec-noite.appspot.com',
    iosBundleId: 'com.example.app03ListaTarefas',
  );
}